---
title: "Stat 400 Final Presentation"
author: "Artie Palen, Jack Allen, Danny Laposata"
date: "12/7/21"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Predicting NBA Player Lines

-For our final project we thought it would be fun to predict NBA betting lines using Monte Carlo Simulation.

-We found an article by Data Scientist Carter Bouley, that creates a model for predicting player scoring lines.

-Using his method, we can compare against bookmakers when sports gambling.

## Background

-As Bouley describes in his article, sports betting relies on an efficient market hypothesis, which means that the prices on any event accurately reflect that events chance of happening.

-In 1906 statistician Francis Galton observed a competition of 800 to guess an ox's weight, he found that while some guesses were high and others low, the average guess (1,197 lb)was extremely close to the weight of the ox (1,198 lb).

-However, this assumption is only valid when there is a high sample size.

## Why use Monte Carlo?

-Monte Carlo simulations rely on repeated sampling to obtain numerical results and are helpful when looking at predicting events where randomness plays a large role, i.e. sports

-Instead of just giving us a result, we can instead get a probability distribution of all the potential results, which is great for sports betting.

-If we can accurately simulate games, we can use it to build our own lines and compare them to the bookmakers. We can then decide if we have something of value.

## Randomness

-Sports have so much randomness and variation as well as limited amounts of data to use. Lineups and coaching is always changing and teams do not preform very consistently from year to year, so historical data is mostly irrelevant.

-The amount of randomness is high from game to game, so looking at one prediction of a game is not very helpful. In order to be successful in sports betting, it doesn't matter what happens in one game, but what happens in 100 or 1000 games. Realizing the outcome over the long run is important.

## Bouley's Results

-Unfortunately, Bouley's code was written in Python so we were unable to transfer his results to this presentation.

-Bouley's article shared a few insights of what influenced the construction of his model.

-He found there was a disparity of amongst points scored by position, on average players would score more points at home versus on the road, and he found a correlation between points scored and minutes played.

-Bouley's large assumption in his model is that points scored by a player is distributed normally. The graphs of points distributions he showed definitely were skewed but fit a normal distribution enough to carry on with his model.

## Bouley's Results (continued)

-The code he wrote takes a multitude of player performance stats that produces an integer result of the projected player scoring line.

-A bettor then compares the projected scoring line to the sportsbook line to see if the odds are favorable.

-If the projection shows that Stephen Curry will score 24 points, and the sportsbook's Over/Under line for Stephen Curry points is 28.5, the bettor would prefer to take the under.

## Bouley's Results (continued)

-In his conclusion he mentions that in order to improve the model, the stats should be weighted by year based on recency. 

-He also notes that the model does not account for non-scoring stats such as assists, rebounds, blocks, steals, etc.

-Finally, Bouley adds that the model does not account for injuries or other external factors. If one were to predict a line for an NBA Finals game, there are many more influencing factors in that game versus a normal regular season game.

## Our Model

-For our model we wanted to create something similar to Bouley's but focus more on team stats rather than individual players.

-For our data we found a data set on Kaggle.com. The data set contains team stats for every game played from the 2014 season through the 2018 season.

-The data set tracks stats such as team points, opponent points, team and opponent field goal totals and percentages, and a few more stats.

-In order to use the data efficiently, we subsetted the data by year and weighted the stats based on recency. 

## Model Assumption

- Similarly to Bouley, we assume that the distribution of points for and points against on a team level is normal.

## Model Construction

-Another assumption that our model makes is that a game outcome can be predicted simply.

-In sports there are hundreds of different factors that could effect the outcome of the game. In basketball, which is 5v5 and a star-dominated sport, something small like the mental health of an individual player could effect the outcome of the game.

-Our model assumes the points scored by a team is equilavent to their average points for added to their opponent's average points against, divided by 2.

## Spread Model

-This model uses Monte Carlo simulation to predict a spread line between any two teams.

-GSW vs CLE example.

## Over/Under Model

-This model uses Monte Carlo Simulation to predict an O/U line between any two teams.

-Note that the two models are constructed very similarly. 

-POR vs LAL example

## Interpretation of the Model

-This model does not violate the normality assumptions, but is built very simply.

-This model is built only using data from 2014-2018. Therefore it is only effective for making a prediction for a game in 2018.

-The construction of this model is very simple and does not predict game outcomes with great accuracy or certainty. Be wary if you this model for your own sports betting purposes.

## Conclusion
