---
title: "Stat 400 Final Presentation"
author: "Artie Palen, Jack Allen, Danny Laposata"
date: "12/7/21"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Predicting NBA Player Lines

For our final project we thought it would be fun to predict NBA player lines using Monte Carlo Simulation.

Using this method, we can predict the stats that a certain player will produce during an NBA game and use that to compare against bookmakers when sports gambling.

## Background

Sports betting relies on an efficient market hypothesis, which means that the prices on any event accurately reflect that events chance of happening.

In 1906 statistician Francis Galton observed a competition of 800 to guess an ox's weight, he found that while some guesses were high and others low, the average guess (1,197 lb)was extremely close to the weight of the ox (1,198 lb).

However, this assumption is only valid when there is a high sample size.

## Why use Monte Carlo?

Monte Carlo simulations rely on repeated sampling to obtain numerical results and are helpful when looking at predicting events where randomness plays a large role, i.e. sports

Instead of just giving us a result, we can instead get a probability distribution of all the potential results, which is great for sports betting.

If we can accurately simulate games, we can use it to build our own lines and compare them to the bookmakers. We can then decide if we have something of value.

## Randomness

Sports have so much randomness and variation as well as limited amounts of data to use. Lineups and coaching is always changing and teams do not preform very consistently from year to year, so historical data is mostly irrelevant.

The amount of randomness is high from game to game, so looking at one prediction of a game is not very helpful. In order to be successful in sports betting, it doesn't matter what happens in one game, but what happens in 100 or 1000 games. Realizing the outcome over the long run is important.
