---
title: "project code"
author: "Kelsey Britton, Theyab Alkhoori"
output: html_document
---

```{r setup}
set.seed(400)
```

```{r article_functions}
paf_single <- function(Pe, RR) {
  AF <- (Pe * (RR - 1)) / (Pe * (RR - 1) + 1)
  return(AF)
}

var_beta_from_CI <- function(RR, Lower, Upper) {
  CIR   <- Upper / Lower
  logse <- log(CIR) / (2 * qnorm(0.975))  
  Var_beta <- logse^2                     
  return(Var_beta)
}

var_Pe <- function(Tp, Pe) {
  Var_Pe <- Pe * (1 - Pe) / Tp 
  return(Var_Pe)
}
```

```{r delta_method}
delta_paf_ci <- function(Tp, Pe, RR, Lower, Upper){
  AF <- paf_single(Pe, RR)
  Var_Pe<- var_Pe(Tp,Pe)
  Var_beta <- var_beta_from_CI(RR, Lower, Upper) 
  
  Delta_Var_AF <- (((RR - 1)^2) * Var_Pe + ((Pe * RR)^2) *
                     Var_beta)/((1 + Pe * (RR - 1))^4)
  
  se <- sqrt(Delta_Var_AF)
  z  <- qnorm(0.975)
  
  low <- AF- (z*se)
  up  <- AF+ (z*se)
  
  out <- c(AF = AF,
           low = low,
           up  = up,
           var = Delta_Var_AF)
  return(out)
}
```

```{r greenland_method}
greenland_paf_ci <- function(Tp, Pe, RR, Lower, Upper){
  AF <- paf_single(Pe, RR)
  Var_Pe<- var_Pe(Tp,Pe)
  Var_beta <- var_beta_from_CI(RR, Lower, Upper) 
  
  O <- Pe / (1 - Pe)
  
  Green_Var_AF <- ((O / Tp) * ((RR - 1)^2 + Var_beta * RR^2)+ Var_beta * O^2 *
                     RR^2) * (1 - AF)^2 / (1 +O)^2
  
  se <- sqrt(Green_Var_AF)
  z  <- qnorm(0.975)
  
  low <- 1-(1-AF) * exp(z*se)
  up  <- 1-(1-AF) * exp(-z*se)
  
  out <- c(AF = AF,
           low = low,
           up  = up,
           var = Green_Var_AF)
  return(out)
}
```

```{r montecarlo_method}
mc_paf_ci <- function(Tp, Pe, RR, Lower, Upper, B= 10000){

  Var_beta <- var_beta_from_CI(RR, Lower, Upper) 
  
  beta<- log(RR)
  
  MonteRR <- rlnorm(B, meanlog = beta, sdlog = sqrt(Var_beta))
  
  MontePe <- rbinom(B, size = Tp, prob = Pe) / Tp
  
  MonteAF <- (MontePe * (MonteRR - 1)) / (1 + MontePe * (MonteRR -1))
  
  AF_est <- median(MonteAF)   
  low <- as.numeric(quantile(MonteAF, 0.025))
  up <- as.numeric(quantile(MonteAF, 0.975))
  
  out <- c(AF = AF_est,
           low = low,
           up  = up)
  return(out)
}
```

### (Replication)

## Scenario A 
```{r A_values}
Tp_A <- 1000
Pe_A <- 0.10
RR_A <- 1.2
Lower_A <- 1.0524696
Upper_A <- 1.368211

true_AF_A <- paf_single(Pe_A, RR_A)
```

```{r A_sim}
delta_A <- delta_paf_ci(Tp_A, Pe_A, RR_A, Lower_A, Upper_A)
green_A<- greenland_paf_ci(Tp_A, Pe_A, RR_A, Lower_A, Upper_A)
mc_A <- mc_paf_ci(Tp_A, Pe_A, RR_A, Lower_A, Upper_A, B = 10000)
```


## Scenario B (strong RR)
```{r B_values}
Tp_B <- 100000
Pe_B <- 0.10
RR_B <- 5.0
Lower_B <- 4.3852901
Upper_B <- 5.700877

true_AF_B <- paf_single(Pe_A, RR_A)
```

```{r B_sim}
delta_B <- delta_paf_ci(Tp_B, Pe_B, RR_B, Lower_B, Upper_B)
green_B<- greenland_paf_ci(Tp_B, Pe_B, RR_B, Lower_B, Upper_B)
mc_B <- mc_paf_ci(Tp_B, Pe_B, RR_B, Lower_B, Upper_B, B = 10000)
```

